export const traded = [
  // Forex Pairs
  { pair: "AUDCAD" },
  { pair: "AUDCHF" },
  { pair: "AUDJPY" },
  { pair: "AUDNZD" },
  { pair: "AUDUSD" },
  { pair: "CADCHF" },
  { pair: "CADJPY" },
  { pair: "CHFJPY" },
  { pair: "EURAUD" },
  { pair: "EURCAD" },
  { pair: "EURCHF" },
  { pair: "EURGBP" },
  { pair: "EURJPY" },
  { pair: "EURNZD" },
  { pair: "EURUSD" },
  { pair: "GBPAUD" },
  { pair: "GBPCAD" },
  { pair: "GBPCHF" },
  { pair: "GBPJPY" },
  { pair: "GBPNZD" },
  { pair: "GBPUSD" },
  { pair: "NZDCAD" },
  { pair: "NZDCHF" },
  { pair: "NZDJPY" },
  { pair: "NZDUSD" },
  { pair: "USDCAD" },
  { pair: "USDCHF" },
  // { pair: "USDJPY" },
  // { pair: "AUDSGD" },
  { pair: "CADSGD" },
  { pair: "CHFSGD" },
  { pair: "EURAED" },
  { pair: "EURCZK" },
  { pair: "EURDKK" },
  { pair: "EURHKD" },
  { pair: "EURHUF" },
  { pair: "EURILS" },
  { pair: "EURINR" },
  { pair: "EURMXN" },
  { pair: "EURNOK" },
  { pair: "EURPLN" },
  { pair: "EURRON" },
  { pair: "EURRUB" },
  { pair: "EURSEK" },
  { pair: "EURSGD" },
  { pair: "EURTRY" },
  { pair: "EURZAR" },
  { pair: "GBPAED" },
  { pair: "GBPCZK" },
  { pair: "GBPDKK" },
  { pair: "GBPHKD" },
  { pair: "GBPHUF" },
  { pair: "GBPINR" },
  { pair: "GBPMXN" },
  { pair: "GBPNOK" },
  { pair: "GBPPLN" },
  { pair: "GBPRON" },
  { pair: "GBPRUB" },
  { pair: "GBPSEK" },
  { pair: "GBPSGD" },
  { pair: "GBPTRY" },
  { pair: "GBPZAR" },
  { pair: "NZDSGD" },
  { pair: "SGDJPY" },
  { pair: "USDCNH" },
  { pair: "USDCZK" },
  { pair: "USDDKK" },
  { pair: "USDHKD" },
  { pair: "USDHUF" },
  { pair: "USDILS" },
  { pair: "USDINR" },
  { pair: "USDMXN" },
  { pair: "USDNOK" },
  { pair: "USDPLN" },
  { pair: "USDRON" },
  { pair: "USDRUB" },
  { pair: "USDSEK" },
  { pair: "USDSGD" },
  { pair: "USDTHB" },
  { pair: "USDTRY" },
  { pair: "USDZAR" },
  { pair: "AUDHKD" },
  { pair: "AUDMXN" },
  { pair: "AUDNOK" },
  { pair: "AUDPLN" },
  { pair: "AUDSEK" },
  { pair: "AEDJPY" },
  { pair: "AUDCZK" },
  { pair: "AUDDKK" },
  { pair: "CHFAUD" },
  { pair: "CHFDKK" },
  { pair: "CHFSEK" },
  { pair: "DKKAUD" },
  { pair: "DKKCHF" },
  { pair: "HKDAUD" },
  { pair: "HKDJPY" },
  { pair: "INRAUD" },
  { pair: "INRJPY" },
  { pair: "JPYAUD" },
  { pair: "JPYHKD" },
  { pair: "JPYINR" },
  { pair: "MXNAUD" },
  { pair: "MXNJPY" },
  { pair: "NOKAUD" },
  { pair: "NOKJPY" },
  { pair: "NZDCAD" },
  { pair: "NZDCHF" },
  { pair: "NZDCZK" },
  { pair: "NZDDKK" },
  { pair: "NZDHKD" },
  { pair: "NZDILS" },
  { pair: "NZDINR" },
  { pair: "NZDMXN" },
  { pair: "NZDNOK" },
  { pair: "NZDPLN" },
  { pair: "NZDSEK" },
  { pair: "NZDSGD" },
  { pair: "NZDTHB" },
  { pair: "NZDTRY" },
  { pair: "NZDZAR" },
  { pair: "SEKAUD" },
  { pair: "SEKJPY" },
  { pair: "SGDAUD" },
  { pair: "SGDCHF" },
  { pair: "SGDJPY" },
  { pair: "THBAUD" },
  { pair: "THBJPY" },
  { pair: "TRYJPY" },
  { pair: "USDHUF" },
  { pair: "USDILS" },
  { pair: "USDJPY" },
  { pair: "USDMXN" },
  { pair: "USDPLN" },
  { pair: "USDSEK" },
  { pair: "USDTHB" },
  { pair: "USDTRY" },
  { pair: "USDZAR" },
  { pair: "ZARJPY" },

  // Indices
  { pair: "US30" }, // Dow Jones Industrial Average
  { pair: "SPX500" }, // S&P 500
  { pair: "NAS100" }, // Nasdaq 100
  { pair: "GER30" }, // DAX 30
  { pair: "UK100" }, // FTSE 100
  { pair: "JP225" }, // Nikkei 225
  { pair: "AUS200" }, // ASX 200
  { pair: "CAC40" }, // CAC 40
  { pair: "HK50" }, // Hang Seng Index
  { pair: "ES35" }, // IBEX 35
  { pair: "IT40" }, // FTSE MIB
  { pair: "CH20" }, // Swiss Market Index

  // Metals
  { pair: "XAGUSD" }, // Silver
  { pair: "XPTUSD" }, // Platinum
  { pair: "XAUUSD" }, // Gold
  { pair: "XPDUSD" }, // Palladium
  { pair: "XAUEUR" }, // Gold/EUR
  { pair: "XAGEUR" }, // Silver/EUR
  { pair: "XAUGBP" }, // Gold/GBP
  { pair: "XAGGBP" }, // Silver/GBP
  { pair: "XAUJPY" }, // Gold/JPY
  { pair: "XAGJPY" }, // Silver/JPY
];
